general:
  app_name: "Python Smart Home Dashboard"
  version: 0.1

app:
  debug: true
  max_fps: 60
  show_fps: true
  locale: "es_ES.UTF-8"
  background_color: [0, 0, 0]

widgets:
  label1:
    visible: true
    type: "simple_label"
    x: 8
    y: 8
    width: 276
    height: 25
    padding: 2
    font_family: "monospace"
    font_size: 16
    font_color: [255, 255, 255]
    text: "Python Smart Home Dashboard"

  label2:
    visible: true
    type: "date"
    x: 8
    y: 38
    width: 750
    height: 34
    padding: 2
    font_family: "monospace"
    font_size: 24
    font_color: [255, 255, 255]
    format_mask: "%A, %d de %B"

  label3:
    visible: true
    type: "time"
    x: 8
    y: 76
    width: 750
    height: 170
    padding: 2
    font_family: "monospace"
    font_size: 150
    font_color: [255, 255, 255]
    format_mask: "%I:%M %p"
