general:
  app_name: "Python Smart Home Dashboard"
  version: 0.1

app:
  debug: true
  max_fps: 60
  fps_counter: "top_right" # top_left | top_right | bottom_left | bottom_right | none
  locale: "es_ES.UTF-8"

widgets:
  label1:
    visible: true
    type: "simple_label"
    x: 500
    y: 500
    width: 64
    height: 64
    padding: 2
    font_family: "monospace"
    font_size: 16
    font_color: [255, 255, 255]
    text: "foobar"

  date1:
    visible: true
    type: "date"
    x: 10
    y: 10
    width: 315
    height: 34
    padding: 2
    font_family: "monospace"
    font_size: 24
    format_mask: "%A, %d de %B"

  time1:
    visible: true
    type: "time"
    x: 10
    y: 60
    width: 318
    height: 80
    padding: 2
    font_family: "monospace"
    font_size: 84
    format_mask: "%I:%M %p"
